#!/bin/bash

#    Embedded System Manager
#    Copyright (C) 2025  Briar Merrett
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.

source /opt/embedded-system-manager/config

case $1 in
  "reset")
    if [ $(id -u) -ne 0 ]; then
        echo "This requires root privileges to run."
        exit 1
    fi
    echo "Resetting embedded-system-deployer service. (scripts will reinstall)"
    systemctl restart embedded-system-deployer.service
    ;;

  "status")
    systemctl status embedded-system-deployer.service
    ;;

  "output")
    journalctl --follow -u embedded-system-deployer.service
    ;;

  "stop")
    if [ $(id -u) -ne 0 ]; then
        echo "This requires root privileges to run."
        exit 1
    fi
    echo "Stopped embedded-system-deployer service."
    systemctl stop embedded-system-deployer.service
    ;;

  "info")
    echo "reading from /opt/embedded-system-deployer/info.txt"
    echo "-----------------------------------"
    cat /opt/embedded-system-manager/info.txt
    echo ""
    ;;

  "config")
    if [ $(id -u) -ne 0 ]; then
        echo "This requires root privileges to run."
        exit 1
    fi
    ${EDITOR:-nano} /opt/embedded-system-manager/config
    ;;

  "configsetup")
    if [ $(id -u) -ne 0 ]; then
        echo "This requires root privileges to run."
        exit 1
    fi
    exec /opt/embedded-system-manager/config_setup.sh
    ;;


  "gotoscripts")
    cd $script_workspace
    ;;

  *)
    printf -- "-- Embedded System Manager --\n
    Arguments:\n
    reset - Restarts the service and refreshes (reclone or pull) the repository.\n
    status - Check systemctl status of the embedded-system-deployer service.\n
    output - Start displaying live output of the embedded-system-deployer service.\n
    stop - Stops the embedded-system-deployer service.\n
    info - Show info.txt in embedded-system-deployer.\n
    config - Open embedded-system-manager config in default editor (${EDITOR:-nano}).\n
    configsetup - Re-run the config setup TUI that was ran on first setup.\n
    gotoscripts - Change current directory to the directory where the downloaded repository is stored.\n
    help - Show this list of command arguments.\n\n" ;;
esac

